### ISSUE TITLE
Figure out how to make download button open up pdf file on new tab

### ISSUE THREAD

**Issue by dieGeisterhand** [dieGeisterhand/about-me#2]

**Comment by Daniel-Diaz** [comment]
```html
<a target="_blank" href="some-url">This opens in a new tab.</a>
```

**Comment by dieGeisterhand** [comment]
Yeah, I know about the target="_blank" line - but I do not know how to not use a separate service to host the file in question. 

Still: We're open source now!

**Comment by dieGeisterhand** [comment]
Figured it out using testing branch. Turns out, it is just like adding a link to something, but pointing to one of your files instead. Just like you'd do with an image!
